# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_auto_20170502_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='image_name',
        ),
        migrations.AddField(
            model_name='location',
            name='picture',
            field=models.FileField(blank=True, upload_to='images'),
        ),
    ]
